### ISSUE TITLE
RDTgauge2 

### ISSUE THREAD

**Issue by Bobbysonic** [i3dm/Zavionix#2]
Hello, I`m running 1.5.13 firmware on my HorusX12S transmitter.  I`m trying your beta widgets V2, all work fine except the RDTgauge. The RDTgauge V1 was replaced as instructed including all the folders.  I tried several times to get this gauge to work, but all I get is a blank yellow screen with several partially loaded images on part of the screen.  All other widgets work perfectly except the RDTgauge!

Thanks, hope this information helps. Excellent work!

Bobby

**Comment by i3dm** [comment]
Thank you for the note.
RDT gauge is only for X20 screen size radios at the moment. I'm working on implementing it for X10 and X18 still.

**Comment by Bobbysonic** [comment]
Thank you for the explanation, great work indeed.

Bobby

**Comment by i3dm** [comment]
Thank you for your feedback
