### ISSUE TITLE
Ethos V2 RDT widget issues

### ISSUE THREAD

**Issue by wfield0455** [i3dm/Zavionix#5]
I installed the Ethos V2 RDT widget on my X20S running Ethos V1.5.15 with a Jetcat version of your RDT and I'm having multiple issues.

1) When transmitter is powered up it trows a Lua error indicated buy red triangle at top of screen.
    clicking on the triangle shows the error as "attempt to compare number with source". When reset it occurs again immediately..
2) As soon at the transmitter is turned on it constantly reports "low fuel".
3) Low fuel report doesn't follow the alarm rate, it simple says low fuel just as fast as it can.
4) Once I power up the Jet and it gets the fuel lever from the ECU instead of 3500ml  it reports 35000ml.

**Comment by wfield0455** [comment]
These issues apear to be installation related. I simply downloaded the latest V2 widget and copied all the files to the existing rdt directory and selecting replace all existing files. It apparently didn't like this. After completely deleting the RDT directory and copying the new one back the the scripts folder on my SD card the lua error is gone and while the low fuel warning does announce before the aircraft is powered on, it only does it every 5 seconds and stops once aircraft is powered. The fuel level still did read 35000ml instead of 3500ml and I correctd this by changing the precision of he DIYA10 sensor to 0.00 instead of 0.0 as indicated in the instructions. It may help others to update the readme file to indicate deltion of any existing RDT directoy and relpacing when upgrading the widget. Also updating the instruction for jetcat ECUs to set precision to 0,.00 would be helpful.

**Comment by i3dm** [comment]
please download latest now (2.1.0) and check again, should be fine.

**Comment by wfield0455** [comment]
Nope, no difference. Works on x20s not on x20proSent from my iPhoneOn Oct 24, 2024, at 9:29 AM, i3dm ***@***.***> wrote:﻿
please download latest now (2.1.0) and check again, should be fine.

**Comment by wfield0455** [comment]
Ok I take it back, it’s working in the x20 pro now too. I decided to copy RDT gauge to my pro and it worked fine, now regular RDT works too.I’ll play with it some more Sent from my iPhoneOn Oct 24, 2024, at 10:22 AM, Wayne Field ***@***.***> wrote:﻿Nope, no difference. Works on x20s not on x20proSent from my iPhoneOn Oct 24, 2024, at 9:29 AM, i3dm ***@***.***> wrote:﻿
please download latest now (2.1.0) and check again, should be fine.

**Comment by wfield0455** [comment]
Ok it’s working now on both x20s and pro. One thing I noticed was a message on debug screen running from ethos suite. When i ran RDTGauge there was a message in it done, x20 pro and some other stuff. That wasn’t displayed when I ran RDT. After running RDT gauge could it have initialized something that makes RDT work properly on the pro too? In any event that message wasn’t displayed when I first ran RDT. Don’t know if that’s significant or not but figured I’d mention it.Wayne Sent from my iPhoneOn Oct 24, 2024, at 10:22 AM, Wayne Field ***@***.***> wrote:﻿Nope, no difference. Works on x20s not on x20proSent from my iPhoneOn Oct 24, 2024, at 9:29 AM, i3dm ***@***.***> wrote:﻿
please download latest now (2.1.0) and check again, should be fine.
